### ISSUE TITLE
release checklist 

### ISSUE THREAD

**Issue by worldsoup** [serverless/serverless-openwhisk#20]
- [x] docs on serverless.com
- [x] coordinate story for posts
- [x] blog post on serverless.com
- [x] blog post on IBM property
- [x] how-to video

**Comment by jthomas** [comment]
I've opened the PR to get the docs on the main site. 
Will move onto these other items now.

**Comment by jthomas** [comment]
- [ ] publish finish version of the plugin to NPM

**Comment by jthomas** [comment]
Docs PR is here:
https://github.com/serverless/serverless/pull/3131
Templates PR is here:
https://github.com/serverless/serverless/pull/3122

**Comment by jthomas** [comment]
Examples PR:
https://github.com/serverless/examples/pull/65

**Comment by jthomas** [comment]
This happened :)
